import React, { Component } from 'react';

import windowFP from '../../assets/plans/SH-Book_08.png';
import details from '../../assets/plans/SH-Book_10.png';

export default class Windows extends Component {
  render() {
    return (
      <div className="page">

        <h3>Windows & Doors</h3>
        <div className="plan-container">
          <img src={windowFP} />
        </div>

        <h3>Details</h3>
        <div className="plan-container">
          <img src={details} />
        </div>

        <h3>Window Schedule</h3>
        <table>
          <thead>
            <tr>
              <td>Label</td>
              <td>Quantity</td>
              <td>Width</td>
              <td>Height</td>
              <td>Type</td>
              <td>Room</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>A</td>
              <td>1</td>
              <td>112"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>B</td>
              <td>5</td>
              <td>96"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>C</td>
              <td>3</td>
              <td>32"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>D</td>
              <td>1</td>
              <td>64"</td>
              <td>48"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>E</td>
              <td>1</td>
              <td>64"</td>
              <td>48"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>F</td>
              <td>1</td>
              <td>64"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>G</td>
              <td>1</td>
              <td>42"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>H</td>
              <td>1</td>
              <td>42"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>I</td>
              <td>2</td>
              <td>16"</td>
              <td>32"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>J</td>
              <td>1</td>
              <td>84"</td>
              <td>96"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>K</td>
              <td>1</td>
              <td>108"</td>
              <td>96"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>L</td>
              <td>1</td>
              <td>112"</td>
              <td>96"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>M</td>
              <td>1</td>
              <td>160"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>N</td>
              <td>1</td>
              <td>34"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>

        <h3>Door Schedule</h3>
        <table>
          <thead>
            <tr>
              <td>Label</td>
              <td>Quantity</td>
              <td>Width</td>
              <td>Height</td>
              <td>Type</td>
              <td>Room</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>a</td>
              <td>3</td>
              <td>80"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>b</td>
              <td>1</td>
              <td>42"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>c</td>
              <td>1</td>
              <td>96"</td>
              <td>96"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>d</td>
              <td>1</td>
              <td>42"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>e</td>
              <td>1</td>
              <td>42"</td>
              <td>84"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>f</td>
              <td>3</td>
              <td>30"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>g</td>
              <td>1</td>
              <td>36"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>h</td>
              <td>1</td>
              <td>36"</td>
              <td>80"</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>i</td>
              <td>1</td>
              <td>192"</td>
              <td>84"</td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>

      </div>
    )
  }
}
